apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-volume
  labels:
    zone: us-est-coast
    clutser: test-clutser1
    rack: rack-22
  annotations:
    build: two
    builder: john-doe
spec:
  containers:
    - name: tets-container
      image: busybox
      imagePullPolicy: Never
      command: ["sh", "-c"]
      args:
        - while true; do
          if [[ -e /etc/labels ]]; then
            echo -en '\n\n'; cat /etc/labels; fi;
          if [[ -e /etc/annotations ]]; then
          echo -en '\n\n'; cat /etc/annotations; fi;
      volumeMounts:
        - mountPath: /etc
          name: podinfo
          readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadta.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadta.annotations