apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-flex-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "yao/nfs"
    fsType: "nfs"
    options:
      server: "192.168.0.114" # 改成你自己的NFS服务器地址
      share: "export"