kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-example
  namespace: default
rules:
  - apiGroups:
      - ""
    verbs:
      - get
      - watch
      - list
    resources:
      - pods
