apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: hello
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kuberneteus cluster
          restartPolicy: OnFailure

  schedule: "*/1 * * * * "