apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-base-promethues-data
  namespace: devops
  labels:
    app: promethues
    environment: prod
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: ""
    fsType: "nfs"
    options:
      server: "192.168.0.114" # 改成你自己的NFS服务器地址
      share: "export"
