apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "monitor"
  name: "promethues"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:


